
location_in = 'D:\ConfocalData\20200228_A1A-RFP_AKT-GFP_37\';
location_out = 'D:\ConfocalData\20200228_A1A-RFP_AKT-GFP_37\MatlabUser3TestApp2\';
file_name = '20200228_A1A-RFP_AKT-GFP_37_';
NameCh1 = 'AKT';
NameCh2 = 'PM stain';
NameCh3 = 'DAPI';
image_type='.tif';
no_channels = 1;
no_sets = 1;

locationExcel = location_out;
filenameExcel = strcat([file_name,'.xlsx']);
sheetName1    = NameCh1;
sheetName2    = NameCh2;
sheetName3    = NameCh3;
ColumnRow     = 'B3';

%         locationExcel = app.location_out;
%         filenameExcel = strcat([app.file_name,'.xlsx']);
%         sheetName     = app.NameCh1;
%         ColumnRow     = 'B3';

pmWidth=6; %(imdilate)
DilateCellRef= 0; %first dilates, second shrink, thired dilate-> size used for calculations

Threshold_Ch1= 'global'
Threshold_Ch2= 'global'
Threshold_Ch3= 'global'
RefProtTheshold='adaptive';
ThresholdRef='adaptive';
ThresholdBG= 'adaptive';
            
ImageNumberForm ='%04d'
NoOfCells = 1
membrane_width = 6;

% channel assignme
% asignment = 1; % Protein, Membrane, Nucleus
% asignment = 2; % Protein, Biosensor, Nucleus

% define cell size
% min_cell_size = 8000
% max_cell_size = 70000

min_cell_size = 5000
max_cell_size = 1000000


% Create a new folder to store the results
%mkdir(app.location_out);

mkdir(location_out);

% main loop
counter = 0;
% for this_set = 1:app.no_sets
for this_set = 1:no_sets
    
    %     image_set = dir(strcat(app.location_in,app.file_name,num2str(this_set),'_*',app.image_type));
    %     if isempty(image_set)
    %         disp(['images ',num2str(this_set),' not found'])
    %         continue;
    %     end
    
    %read image
    %     [Ch1,map1]=imread(strcat(app.location_in,image_set(1).name));
    %     P = Ch1; mapP = map1;
    
    image_set = dir(strcat(location_in,file_name,num2str(this_set,ImageNumberForm),'*',image_type));
    %image_set = dir(strcat(location_in,file_name,num2str(this_set),'_*',image_type));
    if isempty(image_set)
        disp(['images ',num2str(this_set),' not found'])
        continue;
    end
    
   no_channels=3;
   
    % read image
    [P1,mapP1]=imread(strcat(location_in,image_set(1).name));
    if no_channels > 1, [P2,mapP2]=imread(strcat(location_in,image_set(2).name)); end
    if no_channels > 2, [P3,mapP3]=imread(strcat(location_in,image_set(3).name)); end
    
    RP = P1; mapRP =mapP1; RefName='Control';

    
    [SelectedCells,labeledCells,noOfCells] = User3_GetSelectedCells(RefProtTheshold,NoOfCells,RefName,location_out,RP,mapRP,this_set,ThresholdRef,min_cell_size,max_cell_size)
    
    
    for this_cell =1:noOfCells
        [selectedArea,STATSf] = User3_GetAreaOfCells(ThresholdRef,this_cell,labeledCells,RP);
        
        [CellCh1,CellCh2,CellCh3,CellCh1_Int,CellCh1_totalInt,CellCh2_Int,CellCh2_totalInt,CellCh3_Int,CellCh3_totalInt,CellArea,labelthisCell,small,Centroid_xy] = User3_GetCell(NameCh1,NameCh2,NameCh3,location_out,selectedArea,P1,P2,P3,STATSf,this_cell,this_set,DilateCellRef,pmWidth);

        [PMPixNo,PMP1_Int,PMP1_totalInt,PMP2_Int,PMP2_totalInt,PMP3_Int,PMP3_totalInt] = User3_GetPM(NameCh1,NameCh2,NameCh3,location_out,CellArea,small,P1,P2,P3,this_cell,this_set,labelthisCell);
    
        [MarkerAreaP1,MarkerAreaP2,MarkerAreaP3,MarkerPixNoP1,MarkerPixNoP2,MarkerPixNoP3,MarkerP1_P1_Int,MarkerP1_P1_totalInt,MarkerP1_P2_Int,MarkerP1_P2_totalInt,MarkerP1_P3_Int,MarkerP1_P3_totalInt,MarkerP2_P1_Int,MarkerP2_P1_totalInt,MarkerP2_P2_Int,MarkerP2_P2_totalInt,MarkerP2_P3_Int,MarkerP2_P3_totalInt,MarkerP3_P1_Int,MarkerP3_P1_totalInt,MarkerP3_P2_Int,MarkerP3_P2_totalInt,MarkerP3_P3_Int,MarkerP3_P3_totalInt] = User3_GetMarker(NameCh1,NameCh2,NameCh3,location_out,this_cell,this_set,CellCh1,CellCh2,CellCh3,labelthisCell,Threshold_Ch1,Threshold_Ch2,Threshold_Ch3);
          
        [PixNoCellminP1,CellminP1_P1_Int,CellminP1_P1_totalInt,CellminP1_P2_Int,CellminP1_P2_totalInt,CellminP1_P3_Int,CellminP1_P3_totalInt,PixNoCellminP2,CellminP2_P1_Int,CellminP2_P1_totalInt,CellminP2_P2_Int,CellminP2_P2_totalInt, CellminP2_P3_Int,CellminP2_P3_totalInt,PixNoCellminP3,CellminP3_P1_Int,CellminP3_P1_totalInt,CellminP3_P2_Int,CellminP3_P2_totalInt, CellminP3_P3_Int,CellminP3_P3_totalInt] = User3_GetCytoplasm(CellArea,MarkerAreaP1,MarkerAreaP2,MarkerAreaP3,NameCh1,NameCh2,NameCh3,location_out,CellCh1,CellCh2,CellCh3,this_cell,labelthisCell,this_set);

        [pixelBG_P1,minBG_P1,maxBG_P1,meanBG_P1,sumBG_P1,pixelBG_P2,minBG_P2,maxBG_P2,meanBG_P2,sumBG_P2,pixelBG_P3,minBG_P3,maxBG_P3,meanBG_P3,sumBG_P3] = User3_GetBackground(location_out,P1,P2,P3,NameCh1,NameCh2,NameCh3,ThresholdBG,SelectedCells,this_cell,this_set,noOfCells)
%         totalNoOfCells = noOfCells;
        
        counter = counter+1;
             T(counter,:) = table([this_set],[this_cell],...
                        CellCh1_Int.Area,CellCh1_Int.MaxIntensity,CellCh1_Int.MinIntensity,CellCh1_Int.MeanIntensity,CellCh1_totalInt,...
                        PMPixNo,PMP1_Int.MaxIntensity, PMP1_Int.MinIntensity,PMP1_Int.MeanIntensity,PMP1_totalInt,...
                        MarkerPixNoP1,MarkerP1_P1_Int.MaxIntensity,MarkerP1_P1_Int.MinIntensity,MarkerP1_P1_Int.MeanIntensity,MarkerP1_P1_totalInt,...
                        MarkerPixNoP2,MarkerP2_P1_Int.MaxIntensity,MarkerP2_P1_Int.MinIntensity,MarkerP2_P1_Int.MeanIntensity,MarkerP2_P1_totalInt,...
                        MarkerPixNoP3,MarkerP3_P1_Int.MaxIntensity,MarkerP3_P1_Int.MinIntensity,MarkerP3_P1_Int.MeanIntensity,MarkerP3_P1_totalInt,...
                        PixNoCellminP1,CellminP1_P1_Int.MaxIntensity,CellminP1_P1_Int.MinIntensity,CellminP1_P1_Int.MeanIntensity,CellminP1_P1_totalInt,...
                        PixNoCellminP2,CellminP2_P1_Int.MaxIntensity,CellminP2_P1_Int.MinIntensity,CellminP2_P1_Int.MeanIntensity,CellminP2_P1_totalInt,...
                        PixNoCellminP3,CellminP3_P1_Int.MaxIntensity,CellminP3_P1_Int.MinIntensity,CellminP3_P1_Int.MeanIntensity,CellminP3_P1_totalInt,...
                        pixelBG_P1,maxBG_P1,minBG_P1,meanBG_P1,sumBG_P1,...
                        'VariableNames',{'ImageNo','CellNo',...
                        'CellArea','CellmaxInt','CellminInt','CellmeanInt','CelltotalInt',...
                        'PMArea','PMmaxInt','PMminInt','PMmeanInt','PMtotalInt',...
                        'MarkerCh1Area','MarkerCh1maxInt','MarkerCh1minInt','MarkerCh1meanInt','MarkerCh1totalInt',...
                        'MarkerCh2Area','MarkerCh2maxInt','MarkerCh2minInt','MarkerCh2meanInt','MarkerCh2totalInt',...
                        'MarkerCh3Area','MarkerCh3maxInt','MarkerCh3minInt','MarkerCh3meanInt','MarkerCh3totalInt',...
                        'CellwoMarkerCh1Area','CellwoMarkerCh1maxInt','CellwoMarkerCh1minInt','CellwoMarkerCh1meanInt','CellwoMarkerCh1totalInt',...
                        'CellwoMarkerCh2Area','CellwoMarkerCh2maxInt','CellwoMarkerCh2minInt','CellwoMarkerCh2meanInt','CellwoMarkerCh2totalInt',... 
                        'CellwoMarkerCh3Area','CellwoMarkerCh3maxInt','CellwoMarkerCh3minInt','CellwoMarkerCh3meanInt','CellwoMarkerCh3totalInt',... 
                        'BGCh1Area','BGCh1maxInt','BGCh1minInt','BGCh1meanInt','BGCh1totalInt'});
                    
                    T2(counter,:) = table([this_set],[this_cell],...
                        CellCh2_Int.Area,CellCh2_Int.MaxIntensity,CellCh2_Int.MinIntensity,CellCh2_Int.MeanIntensity,CellCh2_totalInt,...
                        PMPixNo,PMP2_Int.MaxIntensity, PMP2_Int.MinIntensity,PMP2_Int.MeanIntensity,PMP2_totalInt,...
                        MarkerPixNoP1,MarkerP1_P2_Int.MaxIntensity,MarkerP1_P2_Int.MinIntensity,MarkerP1_P2_Int.MeanIntensity,MarkerP1_P2_totalInt,...
                        MarkerPixNoP2,MarkerP2_P2_Int.MaxIntensity,MarkerP2_P2_Int.MinIntensity,MarkerP2_P2_Int.MeanIntensity,MarkerP2_P2_totalInt,...
                        MarkerPixNoP3,MarkerP3_P2_Int.MaxIntensity,MarkerP3_P2_Int.MinIntensity,MarkerP3_P2_Int.MeanIntensity,MarkerP3_P2_totalInt,...
                        PixNoCellminP1,CellminP1_P2_Int.MaxIntensity,CellminP1_P2_Int.MinIntensity,CellminP1_P2_Int.MeanIntensity,CellminP1_P2_totalInt,...
                        PixNoCellminP2,CellminP2_P2_Int.MaxIntensity,CellminP2_P2_Int.MinIntensity,CellminP2_P2_Int.MeanIntensity,CellminP2_P2_totalInt,...
                        PixNoCellminP3,CellminP3_P2_Int.MaxIntensity,CellminP3_P2_Int.MinIntensity,CellminP3_P2_Int.MeanIntensity,CellminP3_P2_totalInt,...
                        pixelBG_P2,maxBG_P2,minBG_P2,meanBG_P2,sumBG_P2,...
                        'VariableNames',{'ImageNo','CellNo',...
                        'CellArea','CellmaxInt','CellminInt','CellmeanInt','CelltotalInt',...
                        'PMArea','PMmaxInt','PMminInt','PMmeanInt','PMtotalInt',...
                        'MarkerCh1Area','MarkerCh1maxInt','MarkerCh1minInt','MarkerCh1meanInt','MarkerCh1totalInt',...
                        'MarkerCh2Area','MarkerCh2maxInt','MarkerCh2minInt','MarkerCh2meanInt','MarkerCh2totalInt',...
                        'MarkerCh3Area','MarkerCh3maxInt','MarkerCh3minInt','MarkerCh3meanInt','MarkerCh3totalInt',...
                        'CellwoMarkerCh1Area','CellwoMarkerCh1maxInt','CellwoMarkerCh1minInt','CellwoMarkerCh1meanInt','CellwoMarkerCh1totalInt',...
                        'CellwoMarkerCh2Area','CellwoMarkerCh2maxInt','CellwoMarkerCh2minInt','CellwoMarkerCh2meanInt','CellwoMarkerCh2totalInt',... 
                        'CellwoMarkerCh3Area','CellwoMarkerCh3maxInt','CellwoMarkerCh3minInt','CellwoMarkerCh3meanInt','CellwoMarkerCh3totalInt',... 
                        'BGCh1Area','BGCh1maxInt','BGCh1minInt','BGCh1meanInt','BGCh1totalInt'});
                    
                     T3(counter,:) = table([this_set],[this_cell],...
                        CellCh3_Int.Area,CellCh3_Int.MaxIntensity,CellCh3_Int.MinIntensity,CellCh3_Int.MeanIntensity,CellCh3_totalInt,...
                        PMPixNo,PMP3_Int.MaxIntensity, PMP3_Int.MinIntensity,PMP3_Int.MeanIntensity,PMP3_totalInt,...
                        MarkerPixNoP1,MarkerP1_P3_Int.MaxIntensity,MarkerP1_P3_Int.MinIntensity,MarkerP1_P3_Int.MeanIntensity,MarkerP1_P3_totalInt,...
                        MarkerPixNoP2,MarkerP2_P3_Int.MaxIntensity,MarkerP2_P3_Int.MinIntensity,MarkerP2_P3_Int.MeanIntensity,MarkerP2_P3_totalInt,...
                        MarkerPixNoP3,MarkerP3_P3_Int.MaxIntensity,MarkerP3_P3_Int.MinIntensity,MarkerP3_P3_Int.MeanIntensity,MarkerP3_P3_totalInt,...
                        PixNoCellminP1,CellminP1_P3_Int.MaxIntensity,CellminP1_P3_Int.MinIntensity,CellminP1_P3_Int.MeanIntensity,CellminP1_P3_totalInt,...
                        PixNoCellminP2,CellminP2_P3_Int.MaxIntensity,CellminP2_P3_Int.MinIntensity,CellminP2_P3_Int.MeanIntensity,CellminP2_P3_totalInt,...
                        PixNoCellminP3,CellminP3_P3_Int.MaxIntensity,CellminP3_P3_Int.MinIntensity,CellminP3_P3_Int.MeanIntensity,CellminP3_P3_totalInt,...
                        pixelBG_P3,maxBG_P3,minBG_P3,meanBG_P3,sumBG_P3,...
                        'VariableNames',{'ImageNo','CellNo',...
                        'CellArea','CellmaxInt','CellminInt','CellmeanInt','CelltotalInt',...
                        'PMArea','PMmaxInt','PMminInt','PMmeanInt','PMtotalInt',...
                        'MarkerCh1Area','MarkerCh1maxInt','MarkerCh1minInt','MarkerCh1meanInt','MarkerCh1totalInt',...
                        'MarkerCh2Area','MarkerCh2maxInt','MarkerCh2minInt','MarkerCh2meanInt','MarkerCh2totalInt',...
                        'MarkerCh3Area','MarkerCh3maxInt','MarkerCh3minInt','MarkerCh3meanInt','MarkerCh3totalInt',...
                        'CellwoMarkerCh1Area','CellwoMarkerCh1maxInt','CellwoMarkerCh1minInt','CellwoMarkerCh1meanInt','CellwoMarkerCh1totalInt',...
                        'CellwoMarkerCh2Area','CellwoMarkerCh2maxInt','CellwoMarkerCh2minInt','CellwoMarkerCh2meanInt','CellwoMarkerCh2totalInt',... 
                        'CellwoMarkerCh3Area','CellwoMarkerCh3maxInt','CellwoMarkerCh3minInt','CellwoMarkerCh3meanInt','CellwoMarkerCh3totalInt',... 
                        'BGCh1Area','BGCh1maxInt','BGCh1minInt','BGCh1meanInt','BGCh1totalInt'});
    end
    
    
end
writetable(T,fullfile(locationExcel,filenameExcel),'Sheet',sheetName1,'Range',ColumnRow);

writetable(T2,fullfile(locationExcel,filenameExcel),'Sheet',sheetName2,'Range',ColumnRow);

writetable(T3,fullfile(locationExcel,filenameExcel),'Sheet',sheetName3,'Range',ColumnRow);
